{% set name = "aiida-abinit" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aiida-abinit-{{ version }}.tar.gz
  sha256: 1af665b6bc5288ee9d85f2a2b1c91dd4a13aaafc1bf057a661a4b35e3d5725e2
  patches:
  - pyproject.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - flit-core
    - pip
    - python {{ python_min }}
  run:
    - aiida-core.atomic_tools >=1.6.3,<3.0.0
    - aiida-pseudo >=0.6.1,<2.0.0
    - abipy >=0.8.0
    - importlib_resources
    - packaging
    - python >={{ python_min }}

test:
  imports:
    - aiida_abinit
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sponce24/aiida-abinit
  summary: The AiiDA plugin for ABINIT.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mbercx
    - chrisjsewell
